[build-system]
requires=['setuptools','wheel']
build-backend='setuptools.build_meta'
[project]
name='he-backend'
version='0.0.1'
requires-python='>=3.12'
dependencies=['fastapi','uvicorn[standard]','sqlmodel','alembic','redis','rq','pydantic','python-multipart','prometheus-client','typer']
