# .github/workflows/pr-template-guard.yml
name: pr-template-guard
on:
  pull_request:
    types: [opened, edited, synchronize]
jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.pull_request.body || "";
            const required = ["Summary", "Motivation", "Changes", "Testing", "Checklist"];
            const missing = required.filter(h => !body.toLowerCase().includes(h.toLowerCase()));
            if (missing.length) {
              core.setFailed(`PR description missing sections: ${missing.join(", ")}`);
            }
