name: sbom-scan
on: [push]
jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: anchore/sbom-action@v0
      with:
        path: .
        format: spdx-json
