name: web-ci

on:
  push:
    branches: [ main, feat/**, fix/**, chore/** ]
    paths:
      - 'web/**'
      - '.github/workflows/web-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'web/**'
      - '.github/workflows/web-ci.yml'

permissions:
  contents: read

concurrency:
  group: web-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Install & Build (web)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
          cache-dependency-path: web/pnpm-lock.yaml

      - name: Enable Corepack & pin pnpm
        run: |
          corepack enable
          corepack prepare pnpm@10.15.1 --activate
          pnpm --version
          node --version

      # Installs using the lockfile in web/, honoring .npmrc (allow-scripts for swc/esbuild)
      - name: Install deps
        run: pnpm install --frozen-lockfile

      # Optional: run tests/typecheck if scripts exist (won't fail if missing)
      - name: Unit tests (if present)
        run: pnpm -s test --if-present

      - name: Type check (if present)
        run: pnpm -s typecheck --if-present

      - name: Build
        run: pnpm -s build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: web/dist
          if-no-files-found: error
